// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzbsZydFar7R3_xVrepvcjNt_FgBFuWes',
    appId: '1:903741854299:web:122af5f800f953a9cb657e',
    messagingSenderId: '903741854299',
    projectId: 'my-store-6412a',
    authDomain: 'my-store-6412a.firebaseapp.com',
    storageBucket: 'my-store-6412a.firebasestorage.app',
    measurementId: 'G-MBFLXZ7F8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOzH085tEilEijIgS8XfY9X1hp1Q3ors',
    appId: '1:903741854299:android:f379810c13f3b4f9cb657e',
    messagingSenderId: '903741854299',
    projectId: 'my-store-6412a',
    storageBucket: 'my-store-6412a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyem_ThivNrJWq3Bphtj_BE5V7p_kOW4',
    appId: '1:903741854299:ios:1ecd26f6216cd2aacb657e',
    messagingSenderId: '903741854299',
    projectId: 'my-store-6412a',
    storageBucket: 'my-store-6412a.firebasestorage.app',
    iosClientId: '903741854299-crvpij0ng7sceqnm834uoop26fga02j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyem_ThivNrJWq3Bphtj_BE5V7p_kOW4',
    appId: '1:903741854299:ios:1ecd26f6216cd2aacb657e',
    messagingSenderId: '903741854299',
    projectId: 'my-store-6412a',
    storageBucket: 'my-store-6412a.firebasestorage.app',
    iosClientId: '903741854299-crvpij0ng7sceqnm834uoop26fga02j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzbsZydFar7R3_xVrepvcjNt_FgBFuWes',
    appId: '1:903741854299:web:30e9990e2c0b5f65cb657e',
    messagingSenderId: '903741854299',
    projectId: 'my-store-6412a',
    authDomain: 'my-store-6412a.firebaseapp.com',
    storageBucket: 'my-store-6412a.firebasestorage.app',
    measurementId: 'G-0R1T1EYWE9',
  );
}
